+ module load python
+ unset _mlshdbg
+ '[' 0 = 1 ']'
+ unset _mlre _mlIFS
+ '[' -n x ']'
+ _mlIFS=' 	
'
+ IFS=' '
+ for _mlv in ${MODULES_RUN_QUARANTINE:-}
+ '[' LD_LIBRARY_PATH = LD_LIBRARY_PATH -a LD_LIBRARY_PATH = LD_LIBRARY_PATH ']'
++ eval 'echo ${LD_LIBRARY_PATH+x}'
+++ echo x
+ '[' -n x ']'
++ eval 'echo ${LD_LIBRARY_PATH}'
+++ echo /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
+ _mlre='LD_LIBRARY_PATH_modquar='\''/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib'\'' '
+ _mlrv=MODULES_RUNENV_LD_LIBRARY_PATH
++ eval 'echo ${MODULES_RUNENV_LD_LIBRARY_PATH:-}'
+++ echo
+ _mlre='LD_LIBRARY_PATH_modquar='\''/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib'\'' LD_LIBRARY_PATH='\'''\'' '
+ '[' -n 'LD_LIBRARY_PATH_modquar='\''/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib'\'' LD_LIBRARY_PATH='\'''\'' ' ']'
++ eval 'LD_LIBRARY_PATH_modquar='\''/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib'\''' 'LD_LIBRARY_PATH='\'''\''' /gpfslocalsup/spack_soft/tcl/8.6.8/gcc-4.8.5-5nqkfcnctewdheju62zvqbsonnzszr6m/bin/tclsh /gpfslocalsup/spack_soft/environment-modules/4.3.1/gcc-4.8.5-ism7cdy4xverxywj27jvjstqwk5oxe2v/libexec/modulecmd.tcl bash '"$@"'
+++ LD_LIBRARY_PATH_modquar=/gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
+++ LD_LIBRARY_PATH=
+++ /gpfslocalsup/spack_soft/tcl/8.6.8/gcc-4.8.5-5nqkfcnctewdheju62zvqbsonnzszr6m/bin/tclsh /gpfslocalsup/spack_soft/environment-modules/4.3.1/gcc-4.8.5-ism7cdy4xverxywj27jvjstqwk5oxe2v/libexec/modulecmd.tcl bash load python
+ eval '_LMFILES__modshare=/gpfslocalsup/pub/modules-idris-env4/modulefiles/linux-rhel8-skylake_avx512/python/3.10.4:1;' export '_LMFILES__modshare;
LOADEDMODULES_modshare=python/3.10.4:1;' export 'LOADEDMODULES_modshare;
PYTHONUNBUFFERED=1;' export 'PYTHONUNBUFFERED;
MODULES_LMCONFLICT_modshare=python/3.10.4\&anaconda-py3\&anaconda-py2\&python\&tensorflow-gpu\&pytorch-gpu:1;' export 'MODULES_LMCONFLICT_modshare;
_LMFILES_=/gpfslocalsup/pub/modules-idris-env4/modulefiles/linux-rhel8-skylake_avx512/python/3.10.4;' export '_LMFILES_;
LOADEDMODULES=python/3.10.4;' export 'LOADEDMODULES;
MODULES_LMCONFLICT=python/3.10.4\&anaconda-py3\&anaconda-py2\&python\&tensorflow-gpu\&pytorch-gpu;' export 'MODULES_LMCONFLICT;
.' '/gpfslocalsup/pub/anaconda-py3/2021.05/etc/profile.d/conda.sh;
conda' activate 'python-3.10.4;
test' '0;'
++ _LMFILES__modshare=/gpfslocalsup/pub/modules-idris-env4/modulefiles/linux-rhel8-skylake_avx512/python/3.10.4:1
++ export _LMFILES__modshare
++ LOADEDMODULES_modshare=python/3.10.4:1
++ export LOADEDMODULES_modshare
++ PYTHONUNBUFFERED=1
++ export PYTHONUNBUFFERED
++ MODULES_LMCONFLICT_modshare='python/3.10.4&anaconda-py3&anaconda-py2&python&tensorflow-gpu&pytorch-gpu:1'
++ export MODULES_LMCONFLICT_modshare
++ _LMFILES_=/gpfslocalsup/pub/modules-idris-env4/modulefiles/linux-rhel8-skylake_avx512/python/3.10.4
++ export _LMFILES_
++ LOADEDMODULES=python/3.10.4
++ export LOADEDMODULES
++ MODULES_LMCONFLICT='python/3.10.4&anaconda-py3&anaconda-py2&python&tensorflow-gpu&pytorch-gpu'
++ export MODULES_LMCONFLICT
++ . /gpfslocalsup/pub/anaconda-py3/2021.05/etc/profile.d/conda.sh
+++ export CONDA_EXE=/gpfslocalsup/pub/anaconda-py3/2021.05/bin/conda
+++ CONDA_EXE=/gpfslocalsup/pub/anaconda-py3/2021.05/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/gpfslocalsup/pub/anaconda-py3/2021.05/bin/python
+++ CONDA_PYTHON_EXE=/gpfslocalsup/pub/anaconda-py3/2021.05/bin/python
+++ '[' -z '' ']'
+++ export CONDA_SHLVL=0
+++ CONDA_SHLVL=0
+++ '[' -n '' ']'
+++++ dirname /gpfslocalsup/pub/anaconda-py3/2021.05/bin/conda
++++ dirname /gpfslocalsup/pub/anaconda-py3/2021.05/bin
+++ PATH=/gpfslocalsup/pub/anaconda-py3/2021.05/condabin:/gpfslocalsup/spack_soft/environment-modules/4.3.1/gcc-4.8.5-ism7cdy4xverxywj27jvjstqwk5oxe2v/bin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/c3/bin:/usr/lpp/mmfs/bin:/sbin:/bin:/gpfslocalsys/slurm/current/bin:/gpfslocalsup/bin:/gpfslocalsys/bin:/gpfslocalsys/idrzap/current/bin
+++ export PATH
+++ '[' -z '' ']'
+++ PS1=
++ conda activate python-3.10.4
++ local cmd=activate
++ case "$cmd" in
++ __conda_activate activate python-3.10.4
++ '[' -n '' ']'
++ local ask_conda
+++ PS1=
+++ __conda_exe shell.posix activate python-3.10.4
+++ /gpfslocalsup/pub/anaconda-py3/2021.05/bin/conda shell.posix activate python-3.10.4
++ ask_conda='PS1='\''(python-3.10.4) '\''
export PATH='\''/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/bin:/gpfslocalsup/pub/anaconda-py3/2021.05/condabin:/gpfslocalsup/spack_soft/environment-modules/4.3.1/gcc-4.8.5-ism7cdy4xverxywj27jvjstqwk5oxe2v/bin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/c3/bin:/usr/lpp/mmfs/bin:/sbin:/bin:/gpfslocalsys/slurm/current/bin:/gpfslocalsup/bin:/gpfslocalsys/bin:/gpfslocalsys/idrzap/current/bin'\''
export CONDA_PREFIX='\''/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''python-3.10.4'\''
export CONDA_PROMPT_MODIFIER='\''(python-3.10.4) '\''
export CONDA_EXE='\''/gpfslocalsup/pub/anaconda-py3/2021.05/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/gpfslocalsup/pub/anaconda-py3/2021.05/bin/python'\''
. "/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/gdal-activate.sh"
. "/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/geotiff-activate.sh"
. "/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/libglib_activate.sh"
. "/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/proj4-activate.sh"'
++ eval 'PS1='\''(python-3.10.4) '\''
export PATH='\''/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/bin:/gpfslocalsup/pub/anaconda-py3/2021.05/condabin:/gpfslocalsup/spack_soft/environment-modules/4.3.1/gcc-4.8.5-ism7cdy4xverxywj27jvjstqwk5oxe2v/bin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/c3/bin:/usr/lpp/mmfs/bin:/sbin:/bin:/gpfslocalsys/slurm/current/bin:/gpfslocalsup/bin:/gpfslocalsys/bin:/gpfslocalsys/idrzap/current/bin'\''
export CONDA_PREFIX='\''/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''python-3.10.4'\''
export CONDA_PROMPT_MODIFIER='\''(python-3.10.4) '\''
export CONDA_EXE='\''/gpfslocalsup/pub/anaconda-py3/2021.05/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/gpfslocalsup/pub/anaconda-py3/2021.05/bin/python'\''
. "/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/gdal-activate.sh"
. "/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/geotiff-activate.sh"
. "/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/libglib_activate.sh"
. "/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/proj4-activate.sh"'
+++ PS1='(python-3.10.4) '
+++ export PATH=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/bin:/gpfslocalsup/pub/anaconda-py3/2021.05/condabin:/gpfslocalsup/spack_soft/environment-modules/4.3.1/gcc-4.8.5-ism7cdy4xverxywj27jvjstqwk5oxe2v/bin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/c3/bin:/usr/lpp/mmfs/bin:/sbin:/bin:/gpfslocalsys/slurm/current/bin:/gpfslocalsup/bin:/gpfslocalsys/bin:/gpfslocalsys/idrzap/current/bin
+++ PATH=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/bin:/gpfslocalsup/pub/anaconda-py3/2021.05/condabin:/gpfslocalsup/spack_soft/environment-modules/4.3.1/gcc-4.8.5-ism7cdy4xverxywj27jvjstqwk5oxe2v/bin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/c3/bin:/usr/lpp/mmfs/bin:/sbin:/bin:/gpfslocalsys/slurm/current/bin:/gpfslocalsup/bin:/gpfslocalsys/bin:/gpfslocalsys/idrzap/current/bin
+++ export CONDA_PREFIX=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4
+++ CONDA_PREFIX=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4
+++ export CONDA_SHLVL=1
+++ CONDA_SHLVL=1
+++ export CONDA_DEFAULT_ENV=python-3.10.4
+++ CONDA_DEFAULT_ENV=python-3.10.4
+++ export 'CONDA_PROMPT_MODIFIER=(python-3.10.4) '
+++ CONDA_PROMPT_MODIFIER='(python-3.10.4) '
+++ export CONDA_EXE=/gpfslocalsup/pub/anaconda-py3/2021.05/bin/conda
+++ CONDA_EXE=/gpfslocalsup/pub/anaconda-py3/2021.05/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/gpfslocalsup/pub/anaconda-py3/2021.05/bin/python
+++ CONDA_PYTHON_EXE=/gpfslocalsup/pub/anaconda-py3/2021.05/bin/python
+++ . /gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/gdal-activate.sh
++++ [[ -n '' ]]
++++ [[ -n '' ]]
++++ '[' -d /gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/share/gdal ']'
++++ export GDAL_DATA=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/share/gdal
++++ GDAL_DATA=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/share/gdal
++++ export GDAL_DRIVER_PATH=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/lib/gdalplugins
++++ GDAL_DRIVER_PATH=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/lib/gdalplugins
++++ [[ ! -d /gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/lib/gdalplugins ]]
++++ unset GDAL_DRIVER_PATH
++++ export CPL_ZIP_ENCODING=UTF-8
++++ CPL_ZIP_ENCODING=UTF-8
+++ . /gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/geotiff-activate.sh
++++ [[ -n '' ]]
++++ '[' -d /gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/share/epsg_csv ']'
++++ '[' -d /gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/Library/share/epsg_csv ']'
+++ . /gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/libglib_activate.sh
++++ export GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
++++ GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
++++ export GSETTINGS_SCHEMA_DIR=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/share/glib-2.0/schemas
++++ GSETTINGS_SCHEMA_DIR=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/share/glib-2.0/schemas
+++ . /gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/etc/conda/activate.d/proj4-activate.sh
++++ '[' -n '' ']'
++++ '[' -d /gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/share/proj ']'
++++ export PROJ_LIB=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/share/proj
++++ PROJ_LIB=/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/share/proj
++++ '[' -f /gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/share/proj/copyright_and_licenses.csv ']'
++++ export PROJ_NETWORK=ON
++++ PROJ_NETWORK=ON
++ __conda_hashr
++ '[' -n '' ']'
++ '[' -n '' ']'
++ hash -r
++ test 0
+ _mlstatus=0
+ '[' -n x ']'
+ IFS=' 	
'
+ unset _mlre _mlv _mlrv _mlIFS
+ '[' -n '' ']'
+ unset _mlshdbg
+ return 0
+ export PATH=/gpfswork/rech/btm/uei84ht/.local/bin:/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/bin:/gpfslocalsup/pub/anaconda-py3/2021.05/condabin:/gpfslocalsup/spack_soft/environment-modules/4.3.1/gcc-4.8.5-ism7cdy4xverxywj27jvjstqwk5oxe2v/bin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/c3/bin:/usr/lpp/mmfs/bin:/sbin:/bin:/gpfslocalsys/slurm/current/bin:/gpfslocalsup/bin:/gpfslocalsys/bin:/gpfslocalsys/idrzap/current/bin
+ PATH=/gpfswork/rech/btm/uei84ht/.local/bin:/gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/bin:/gpfslocalsup/pub/anaconda-py3/2021.05/condabin:/gpfslocalsup/spack_soft/environment-modules/4.3.1/gcc-4.8.5-ism7cdy4xverxywj27jvjstqwk5oxe2v/bin:/opt/clmgr/sbin:/opt/clmgr/bin:/opt/sgi/sbin:/opt/sgi/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/c3/bin:/usr/lpp/mmfs/bin:/sbin:/bin:/gpfslocalsys/slurm/current/bin:/gpfslocalsup/bin:/gpfslocalsys/bin:/gpfslocalsys/idrzap/current/bin
+ accelerate launch --config_file LEGAL-PE/SIGIR_experiments/distributedTraining/Config_files_for_distributed/default_accelerate_config_without_deep_speed.yaml LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py --maxlen 128 --length 126 --overlap 125 --loading_model_path LEGAL-P_E/SIGIR_experiments/finetuned_models/ecthr_b/EleutherAI_gpt-neo-1.3B/Strategy_0/sub_strategy_0/ZeRO3_epoch_2__final/pytorch_model.bin --cuda_number 0 --strat 0 --dataset_subset ecthr_b --hggfc_model_name EleutherAI/gpt-neo-1.3B --get_train_data True --get_validation_data True --get_test_data True --trained_with_deepspeed_accelerate True --path_train_dat LEGAL-P_E/SIGIR_experiments/finetuned_models/ecthr_b/Extracted_data/from_512input_ft_model/128_input_len_25_overlap/Neo1.3b/
2023-05-25 13:55:13.028674: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-25 13:55:14.278251: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-05-25 13:55:15.027253: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-25 13:55:24.061495: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:55:24.061668: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:55:24.061687: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-05-25 13:56:42.029962: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-25 13:56:42.030098: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-25 13:56:42.031453: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-25 13:56:42.039742: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-25 13:56:42.039745: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-25 13:56:42.040236: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-25 13:56:49.347192: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.347196: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.347237: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.347379: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.347379: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.351211: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-05-25 13:56:49.347378: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.347378: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.351461: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.351505: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-05-25 13:56:49.351519: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.351563: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-05-25 13:56:49.351585: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.351627: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-05-25 13:56:49.351633: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.351657: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /gpfslocalsys/slurm/current/lib/slurm:/gpfslocalsys/slurm/current/lib
2023-05-25 13:56:49.352295: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-05-25 13:56:49.352306: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Extraction started!
Extraction started!

Extraction started!

Extraction started!

Extraction for ecthr_b started!Extraction started!

Extraction started!

Extraction for ecthr_b started!



Extraction for ecthr_b started!


Extraction for ecthr_b started!
Extraction for ecthr_b started!

Extraction for ecthr_b started!



Dataset's slice view:

Dataset's slice view:

Dataset's slice view:


Dataset's slice view:


Dataset's slice view:

Dataset's slice view:




                                                   text     labels
0     [11.  At the beginning of the events relevant ...        [4]
1     [9.  The applicant is the monarch of Liechtens...  [8, 3, 9]
2     [9.  In June 1949 plots of agricultural land o...        [3]
3     [8.  In 1991 Mr Dušan Slobodník, a research wo...  [6, 8, 5]
4     [9.  The applicant is an Italian citizen, born...     [8, 3]
...                                                 ...        ...
8995  [5.  The applicant was born in 1960 and lives ...     [3, 4]
8996  [5.  The applicant was born in 1946 and is cur...         []
8997  [5.  The applicants are Russian nationals who,...  [0, 1, 2]
8998  [8.  In all cases the applicants brought civil...     [3, 9]
8999  [4.  The applicant was born in 1971 and lives ...        [3]

[9000 rows x 2 columns]                                                   text     labels
0     [11.  At the beginning of the events relevant ...        [4]
1     [9.  The applicant is the monarch of Liechtens...  [8, 3, 9]
2     [9.  In June 1949 plots of agricultural land o...        [3]
3     [8.  In 1991 Mr Dušan Slobodník, a research wo...  [6, 8, 5]
4     [9.  The applicant is an Italian citizen, born...     [8, 3]
...                                                 ...        ...
8995  [5.  The applicant was born in 1960 and lives ...     [3, 4]
8996  [5.  The applicant was born in 1946 and is cur...         []
8997  [5.  The applicants are Russian nationals who,...  [0, 1, 2]
8998  [8.  In all cases the applicants brought civil...     [3, 9]
8999  [4.  The applicant was born in 1971 and lives ...        [3]

[9000 rows x 2 columns]

                                                   text     labels
0     [11.  At the beginning of the events relevant ...        [4]
1     [9.  The applicant is the monarch of Liechtens...  [8, 3, 9]
2     [9.  In June 1949 plots of agricultural land o...        [3]
3     [8.  In 1991 Mr Dušan Slobodník, a research wo...  [6, 8, 5]
4     [9.  The applicant is an Italian citizen, born...     [8, 3]
...                                                 ...        ...
8995  [5.  The applicant was born in 1960 and lives ...     [3, 4]
8996  [5.  The applicant was born in 1946 and is cur...         []
8997  [5.  The applicants are Russian nationals who,...  [0, 1, 2]
8998  [8.  In all cases the applicants brought civil...     [3, 9]
8999  [4.  The applicant was born in 1971 and lives ...        [3]

[9000 rows x 2 columns]                                                   text     labels
0     [11.  At the beginning of the events relevant ...        [4]
1     [9.  The applicant is the monarch of Liechtens...  [8, 3, 9]
2     [9.  In June 1949 plots of agricultural land o...        [3]
3     [8.  In 1991 Mr Dušan Slobodník, a research wo...  [6, 8, 5]
4     [9.  The applicant is an Italian citizen, born...     [8, 3]
...                                                 ...        ...
8995  [5.  The applicant was born in 1960 and lives ...     [3, 4]
8996  [5.  The applicant was born in 1946 and is cur...         []
8997  [5.  The applicants are Russian nationals who,...  [0, 1, 2]
8998  [8.  In all cases the applicants brought civil...     [3, 9]
8999  [4.  The applicant was born in 1971 and lives ...        [3]

[9000 rows x 2 columns]

                                                   text     labels
0     [11.  At the beginning of the events relevant ...        [4]
1     [9.  The applicant is the monarch of Liechtens...  [8, 3, 9]
2     [9.  In June 1949 plots of agricultural land o...        [3]
3     [8.  In 1991 Mr Dušan Slobodník, a research wo...  [6, 8, 5]
4     [9.  The applicant is an Italian citizen, born...     [8, 3]
...                                                 ...        ...
8995  [5.  The applicant was born in 1960 and lives ...     [3, 4]
8996  [5.  The applicant was born in 1946 and is cur...         []
8997  [5.  The applicants are Russian nationals who,...  [0, 1, 2]
8998  [8.  In all cases the applicants brought civil...     [3, 9]
8999  [4.  The applicant was born in 1971 and lives ...        [3]

[9000 rows x 2 columns]                                                   text     labels
0     [11.  At the beginning of the events relevant ...        [4]
1     [9.  The applicant is the monarch of Liechtens...  [8, 3, 9]
2     [9.  In June 1949 plots of agricultural land o...        [3]
3     [8.  In 1991 Mr Dušan Slobodník, a research wo...  [6, 8, 5]
4     [9.  The applicant is an Italian citizen, born...     [8, 3]
...                                                 ...        ...
8995  [5.  The applicant was born in 1960 and lives ...     [3, 4]
8996  [5.  The applicant was born in 1946 and is cur...         []
8997  [5.  The applicants are Russian nationals who,...  [0, 1, 2]
8998  [8.  In all cases the applicants brought civil...     [3, 9]
8999  [4.  The applicant was born in 1971 and lives ...        [3]

[9000 rows x 2 columns]

  0%|          | 0/9000 [00:00<?, ?it/s]  0%|          | 0/9000 [00:00<?, ?it/s]  0%|          | 0/9000 [00:00<?, ?it/s]  0%|          | 0/9000 [00:00<?, ?it/s]  0%|          | 0/9000 [00:00<?, ?it/s]  0%|          | 0/9000 [00:00<?, ?it/s]  6%|▌         | 557/9000 [00:00<00:01, 5566.82it/s]  9%|▉         | 842/9000 [00:00<00:00, 8417.78it/s]  9%|▉         | 850/9000 [00:00<00:00, 8495.75it/s]  6%|▌         | 552/9000 [00:00<00:01, 5516.06it/s]  9%|▉         | 840/9000 [00:00<00:00, 8392.50it/s]  9%|▉         | 846/9000 [00:00<00:00, 8451.18it/s] 14%|█▍        | 1246/9000 [00:00<00:01, 6343.30it/s] 19%|█▉        | 1741/9000 [00:00<00:00, 8753.05it/s] 20%|█▉        | 1761/9000 [00:00<00:00, 8856.21it/s] 14%|█▍        | 1256/9000 [00:00<00:01, 6410.23it/s] 19%|█▉        | 1737/9000 [00:00<00:00, 8727.84it/s] 19%|█▉        | 1753/9000 [00:00<00:00, 8810.62it/s] 25%|██▍       | 2207/9000 [00:00<00:00, 7830.75it/s] 29%|██▉       | 2654/9000 [00:00<00:00, 8923.85it/s] 30%|██▉       | 2681/9000 [00:00<00:00, 9008.99it/s] 24%|██▍       | 2196/9000 [00:00<00:00, 7774.54it/s] 29%|██▉       | 2644/9000 [00:00<00:00, 8881.85it/s] 30%|██▉       | 2676/9000 [00:00<00:00, 9000.47it/s] 35%|███▍      | 3138/9000 [00:00<00:00, 8411.07it/s] 40%|███▉      | 3573/9000 [00:00<00:00, 9026.96it/s] 40%|███▉      | 3599/9000 [00:00<00:00, 9074.48it/s] 39%|███▉      | 3551/9000 [00:00<00:00, 8955.58it/s] 33%|███▎      | 2974/9000 [00:00<00:00, 6974.66it/s] 40%|███▉      | 3577/9000 [00:00<00:00, 7628.04it/s] 45%|████▌     | 4052/9000 [00:00<00:00, 8671.35it/s] 50%|████▉     | 4494/9000 [00:00<00:00, 9089.38it/s] 50%|█████     | 4516/9000 [00:00<00:00, 9107.79it/s] 50%|████▉     | 4458/9000 [00:00<00:00, 8996.73it/s] 43%|████▎     | 3862/9000 [00:00<00:00, 7613.70it/s] 50%|████▉     | 4487/9000 [00:00<00:00, 8102.64it/s] 55%|█████▌    | 4963/9000 [00:00<00:00, 8817.12it/s] 60%|██████    | 5427/9000 [00:00<00:00, 9170.37it/s] 60%|██████    | 5427/9000 [00:00<00:00, 8376.24it/s] 60%|█████▉    | 5358/9000 [00:00<00:00, 8329.29it/s] 53%|█████▎    | 4767/9000 [00:00<00:00, 8078.52it/s] 60%|██████    | 5400/9000 [00:00<00:00, 8424.97it/s] 65%|██████▌   | 5879/9000 [00:00<00:00, 8927.01it/s] 71%|███████   | 6349/9000 [00:00<00:00, 9183.43it/s] 71%|███████   | 6346/9000 [00:00<00:00, 8626.80it/s] 70%|██████▉   | 6263/9000 [00:00<00:00, 8552.19it/s] 63%|██████▎   | 5669/9000 [00:00<00:00, 8375.66it/s] 70%|███████   | 6310/9000 [00:00<00:00, 8632.93it/s] 75%|███████▌  | 6794/9000 [00:00<00:00, 8996.92it/s] 81%|████████  | 7272/9000 [00:00<00:00, 9197.81it/s] 81%|████████  | 7265/9000 [00:00<00:00, 8799.01it/s] 80%|███████▉  | 7178/9000 [00:00<00:00, 8733.10it/s] 73%|███████▎  | 6571/9000 [00:00<00:00, 8575.25it/s] 80%|████████  | 7223/9000 [00:00<00:00, 8783.97it/s] 86%|████████▌ | 7710/9000 [00:00<00:00, 9045.43it/s] 91%|█████████ | 8194/9000 [00:00<00:00, 9204.10it/s] 91%|█████████ | 8184/9000 [00:00<00:00, 8916.38it/s] 90%|████████▉ | 8092/9000 [00:00<00:00, 8856.41it/s] 83%|████████▎ | 7470/9000 [00:00<00:00, 8701.10it/s] 90%|█████████ | 8135/9000 [00:00<00:00, 8884.74it/s]100%|██████████| 9000/9000 [00:00<00:00, 9110.08it/s]
  0%|          | 0/1000 [00:00<?, ?it/s] 96%|█████████▌| 8627/9000 [00:01<00:00, 9081.31it/s]100%|██████████| 9000/9000 [00:01<00:00, 8867.90it/s]
  0%|          | 0/1000 [00:00<?, ?it/s]100%|██████████| 9000/9000 [00:01<00:00, 8795.81it/s]
  0%|          | 0/1000 [00:00<?, ?it/s] 93%|█████████▎| 8371/9000 [00:01<00:00, 8793.73it/s]100%|██████████| 9000/9000 [00:01<00:00, 8640.07it/s]
  0%|          | 0/1000 [00:00<?, ?it/s]100%|██████████| 9000/9000 [00:01<00:00, 8646.78it/s]
  0%|          | 0/1000 [00:00<?, ?it/s] 88%|████████▊ | 882/1000 [00:00<00:00, 8810.85it/s]100%|██████████| 9000/9000 [00:01<00:00, 8187.50it/s]
100%|██████████| 1000/1000 [00:00<00:00, 8845.61it/s]
  0%|          | 0/1000 [00:00<?, ?it/s]  0%|          | 0/1000 [00:00<?, ?it/s] 92%|█████████▏| 915/1000 [00:00<00:00, 9143.90it/s]100%|██████████| 1000/1000 [00:00<00:00, 9128.61it/s]
 90%|█████████ | 903/1000 [00:00<00:00, 9023.55it/s]  0%|          | 0/1000 [00:00<?, ?it/s]100%|██████████| 1000/1000 [00:00<00:00, 9010.57it/s]
  0%|          | 0/1000 [00:00<?, ?it/s] 92%|█████████▏| 918/1000 [00:00<00:00, 9173.14it/s] 92%|█████████▏| 916/1000 [00:00<00:00, 9151.98it/s]100%|██████████| 1000/1000 [00:00<00:00, 9158.49it/s]
  0%|          | 0/1000 [00:00<?, ?it/s]100%|██████████| 1000/1000 [00:00<00:00, 9138.57it/s]
  0%|          | 0/1000 [00:00<?, ?it/s] 90%|█████████ | 900/1000 [00:00<00:00, 8991.41it/s] 91%|█████████ | 909/1000 [00:00<00:00, 9080.76it/s]100%|██████████| 1000/1000 [00:00<00:00, 9067.08it/s]
100%|██████████| 1000/1000 [00:00<00:00, 8972.83it/s]
  0%|          | 0/1000 [00:00<?, ?it/s] 93%|█████████▎| 928/1000 [00:00<00:00, 9278.88it/s]100%|██████████| 1000/1000 [00:00<00:00, 9263.67it/s]
 91%|█████████ | 912/1000 [00:00<00:00, 9113.88it/s]100%|██████████| 1000/1000 [00:00<00:00, 9100.74it/s]
 92%|█████████▏| 924/1000 [00:00<00:00, 9235.96it/s] 92%|█████████▏| 916/1000 [00:00<00:00, 9151.67it/s]100%|██████████| 1000/1000 [00:00<00:00, 9218.80it/s]
100%|██████████| 1000/1000 [00:00<00:00, 9137.00it/s]
 90%|████████▉ | 897/1000 [00:00<00:00, 8961.01it/s]100%|██████████| 1000/1000 [00:00<00:00, 8932.17it/s]

Loading EleutherAI/gpt-neo-1.3B model and tokenizer

Loading EleutherAI/gpt-neo-1.3B model and tokenizer

Loading EleutherAI/gpt-neo-1.3B model and tokenizer

Loading EleutherAI/gpt-neo-1.3B model and tokenizer

Loading EleutherAI/gpt-neo-1.3B model and tokenizer

Loading EleutherAI/gpt-neo-1.3B model and tokenizer
{'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}{'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}


Tokenizer Loaded
Tokenizer Loaded
{'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}


Tokenizer Loaded
{'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}

Tokenizer Loaded
{'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}

Tokenizer Loaded
{'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}

Tokenizer Loaded
Some weights of GPTNeoForSequenceClassification were not initialized from the model checkpoint at /gpfsdswork/dataset/HuggingFace_Models/EleutherAI/gpt-neo-1.3B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of GPTNeoForSequenceClassification were not initialized from the model checkpoint at /gpfsdswork/dataset/HuggingFace_Models/EleutherAI/gpt-neo-1.3B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of GPTNeoForSequenceClassification were not initialized from the model checkpoint at /gpfsdswork/dataset/HuggingFace_Models/EleutherAI/gpt-neo-1.3B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 761, in <module>
  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 761, in <module>
Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 761, in <module>
    main()
  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 645, in main
        main()main()

  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 645, in main
  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 645, in main
    model.load_state_dict(torch.load(args.loading_model_path))
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    model.load_state_dict(torch.load(args.loading_model_path))    
model.load_state_dict(torch.load(args.loading_model_path))  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 791, in load

  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
        with _open_file_like(f, 'rb') as opened_file:with _open_file_like(f, 'rb') as opened_file:

      File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
with _open_file_like(f, 'rb') as opened_file:
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)    
return _open_file(name_or_buffer, mode)      File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__

return _open_file(name_or_buffer, mode)  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__

  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError    : super().__init__(open(name, mode))[Errno 2] No such file or directory: 'LEGAL-P_E/SIGIR_experiments/finetuned_models/ecthr_b/EleutherAI_gpt-neo-1.3B/Strategy_0/sub_strategy_0/ZeRO3_epoch_2__final/pytorch_model.bin'

    FileNotFoundErrorsuper().__init__(open(name, mode)): 
[Errno 2] No such file or directory: 'LEGAL-P_E/SIGIR_experiments/finetuned_models/ecthr_b/EleutherAI_gpt-neo-1.3B/Strategy_0/sub_strategy_0/ZeRO3_epoch_2__final/pytorch_model.bin'FileNotFoundError
: [Errno 2] No such file or directory: 'LEGAL-P_E/SIGIR_experiments/finetuned_models/ecthr_b/EleutherAI_gpt-neo-1.3B/Strategy_0/sub_strategy_0/ZeRO3_epoch_2__final/pytorch_model.bin'
Some weights of GPTNeoForSequenceClassification were not initialized from the model checkpoint at /gpfsdswork/dataset/HuggingFace_Models/EleutherAI/gpt-neo-1.3B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of GPTNeoForSequenceClassification were not initialized from the model checkpoint at /gpfsdswork/dataset/HuggingFace_Models/EleutherAI/gpt-neo-1.3B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 761, in <module>
    main()
  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 645, in main
    model.load_state_dict(torch.load(args.loading_model_path))
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'LEGAL-P_E/SIGIR_experiments/finetuned_models/ecthr_b/EleutherAI_gpt-neo-1.3B/Strategy_0/sub_strategy_0/ZeRO3_epoch_2__final/pytorch_model.bin'
Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 761, in <module>
    main()
  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 645, in main
    model.load_state_dict(torch.load(args.loading_model_path))
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'LEGAL-P_E/SIGIR_experiments/finetuned_models/ecthr_b/EleutherAI_gpt-neo-1.3B/Strategy_0/sub_strategy_0/ZeRO3_epoch_2__final/pytorch_model.bin'
Some weights of GPTNeoForSequenceClassification were not initialized from the model checkpoint at /gpfsdswork/dataset/HuggingFace_Models/EleutherAI/gpt-neo-1.3B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 761, in <module>
    main()
  File "/gpfsdswork/projects/rech/btm/uei84ht/LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py", line 645, in main
    model.load_state_dict(torch.load(args.loading_model_path))
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'LEGAL-P_E/SIGIR_experiments/finetuned_models/ecthr_b/EleutherAI_gpt-neo-1.3B/Strategy_0/sub_strategy_0/ZeRO3_epoch_2__final/pytorch_model.bin'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 534048) of binary: /gpfslocalsup/pub/anaconda-py3/2021.05/envs/python-3.10.4/bin/python3.10
Traceback (most recent call last):
  File "/gpfswork/rech/btm/uei84ht/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 909, in launch_command
    multi_gpu_launcher(args)
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 604, in multi_gpu_launcher
    distrib_run.run(args)
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/linkhome/rech/geniri01/uei84ht/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
LEGAL-PE/SIGIR_experiments/datasets/extract_CLS_embeds_after_finetuning_.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-05-25_13:57:47
  host      : jean-zay-ia831-ib0
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 534049)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-05-25_13:57:47
  host      : jean-zay-ia831-ib0
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 534050)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-05-25_13:57:47
  host      : jean-zay-ia831-ib0
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 534051)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2023-05-25_13:57:47
  host      : jean-zay-ia831-ib0
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 534052)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2023-05-25_13:57:47
  host      : jean-zay-ia831-ib0
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 534053)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-25_13:57:47
  host      : jean-zay-ia831-ib0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 534048)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
